services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/bezkoder_db

volumes:
  mongo_data:
 
